trigger:
- dev
pool:
 vmImage: ubuntu
variables:
- group: azure-group
- name: IMAGE_TAG
  value: $(Build.BuildId)
- name: FULL_IMAGE
  value: '$(REGION)-docker.pkg.dev/$(PROJECT_ID)/$(REPO)/$(IMAGE_NAME):$(IMAGE_TAG)'
- name: LATEST_IMAGE
  value: '$(REGISTRY_URL)/$(PROJECT_ID)/$(REPO)/$(IMAGE_NAME):latest'
stages:
- stage: BuildAndPush
  jobs:
  - job: Push
    steps:
    - task: DownloadSecureFile@1
      name: gcpKey
      inputs:
        secureFile: 'gcp-key.json'
    - task: GoogleCloudSdkTool@1
      inputs:
        versionSpec: '315.x'
        checkLatest: true
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Bash@3
      displayName: "Authenticate to GCP and Configure Docker"
      inputs:
        targetType: 'inline'
        script: |
          gcloud auth activate-service-account --key-file=$(gcpKey.secureFilePath)
          gcloud auth configure-docker $(REGISTRY_URL) -q
    - task: Bash@3
      displayName: "Build Docker Image"
      inputs:
        targetType: 'inline'
        script: |
          echo "Building image: $(FULL_IMAGE)"
          docker build -t $(FULL_IMAGE) .
    - task: Bash@3
      displayName: "Push Docker Image"
      inputs:
        targetType: 'inline'
        script: |
            docker tag $(FULL_IMAGE) $(LATEST_IMAGE)
            echo "Pushing image: $(FULL_IMAGE)"
            docker push $(FULL_IMAGE)
            docker push $(LATEST_IMAGE)