spring:
  application:
    name: notification-service
  datasource:
    password: iiitn123
    url: jdbc:mysql:///notification-service?cloudSqlInstance=fluted-factor-438905-d2:us-west1:intern-tracker&socketFactory=com.google.cloud.sql.mysql.SocketFactory

    username: root
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8084
